name: Scan Server Package

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan-server:
    uses: ./.github/workflows/sonarqube.yml
    permissions: read-all
    with:
      args: >
        -Dsonar.projectKey=monorepo-server
        -Dsonar.projectBaseDir=packages/simple-express-server
    secrets: inherit
