name: Scan Server Package

on:
  push:
    branches:
      - master
    paths:
      - packages/simple-express-server
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - packages/simple-express-server

jobs:
  scan-server:
    uses: ./.github/workflows/sonarqube.yml
    permissions: read-all
    with:
      args: >
        -Dsonar.projectBaseDir=${{ on.push.paths }}
        -Dsonar.projectKey=monorepo-server
    secrets: inherit
