name: Scan Server Package

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan-server:
    uses: ./.github/workflows/sonarqube.yml
    with:
      scanner-opts: -Dsonar.projectKey=monorepo-server
    secrets: inherit
